### ISSUE TITLE
demo.pth.tar error

### ISSUE THREAD

**Issue by DongfeiJi** [ayumiymk/aster.pytorch#23] opened 2019-10-07 10:00 UTC
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
Dear author:
how can i sovle this problem, thanks for answer.

**Comment by ayumiymk** [comment] 2019-10-07 11:51
Duplicate of #18

**Closed** 2019-10-07 11:51 UTC

**Comment by DongfeiJi** [comment] 2019-10-07 11:59
what's happened...




------------------ 原始邮件 ------------------
发件人: "Mingkun Yang"<notifications@github.com>; 
发送时间: 2019年10月7日(星期一) 晚上7:51
收件人: "ayumiymk/aster.pytorch"<aster.pytorch@noreply.github.com>; 
抄送: "dongfei"<648513181@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ayumiymk/aster.pytorch] demo.pth.tar error (#23)




Closed #23.
 
&mdash;

**Comment by ayumiymk** [comment] 2019-10-08 03:31
The same question has been solved in #18, please refer to it.

**Comment by DongfeiJi** [comment] 2019-10-08 07:33
Thanks，it helps a lot.



------------------ Original ------------------
